/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    businesses: Business;
    sectors: Sector;
    news: News;
    'impact-programmes': ImpactProgramme;
    leadership: Leadership;
    pages: Page;
    enquiries: Enquiry;
    media: Media;
    users: User;
    redirects: Redirect;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    businesses: BusinessesSelect<false> | BusinessesSelect<true>;
    sectors: SectorsSelect<false> | SectorsSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    'impact-programmes': ImpactProgrammesSelect<false> | ImpactProgrammesSelect<true>;
    leadership: LeadershipSelect<false> | LeadershipSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    enquiries: EnquiriesSelect<false> | EnquiriesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    homepage: Homepage;
    'media-kit': MediaKit;
    'site-settings': SiteSetting;
    header: Header;
    footer: Footer;
  };
  globalsSelect: {
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    'media-kit': MediaKitSelect<false> | MediaKitSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Each business has its own page at /businesses/[slug].
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "businesses".
 */
export interface Business {
  id: number;
  name: string;
  /**
   * One line under the name, about 12 words.
   */
  tagline?: string | null;
  /**
   * One or two sentences, shown on cards and in search results.
   */
  summary: string;
  logo?: (number | null) | Media;
  heroImage?: (number | null) | Media;
  overview?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  services?:
    | {
        title: string;
        description?: string | null;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  stats?:
    | {
        /**
         * e.g. 16, 250+, 24/7
         */
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  gallery?: (number | Media)[] | null;
  layout?:
    | (RatesTableBlock | LoanProductsBlock | ProductListBlock | RoomsBlock | FAQBlock | CTABlock | RichTextBlock)[]
    | null;
  locations?:
    | {
        name: string;
        district?:
          | (
              | 'western-area-urban'
              | 'western-area-rural'
              | 'bo'
              | 'bombali'
              | 'bonthe'
              | 'falaba'
              | 'kailahun'
              | 'kambia'
              | 'karene'
              | 'kenema'
              | 'koinadugu'
              | 'kono'
              | 'moyamba'
              | 'port-loko'
              | 'pujehun'
              | 'tonkolili'
            )
          | null;
        address?: string | null;
        phone?: string | null;
        /**
         * e.g. Mon–Sat 8am–8pm
         */
        hours?: string | null;
        lat?: number | null;
        lng?: number | null;
        id?: string | null;
      }[]
    | null;
  contact?: {
    phone?: string | null;
    /**
     * International format, e.g. +23276000000
     */
    whatsapp?: string | null;
    email?: string | null;
    /**
     * Not shown on the site. Website enquiries are emailed here.
     */
    enquiryEmail?: string | null;
  };
  socials?: {
    facebook?: string | null;
    instagram?: string | null;
    linkedin?: string | null;
    tiktok?: string | null;
    x?: string | null;
    youtube?: string | null;
  };
  /**
   * Optional, if the business has its own site.
   */
  website?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  sector: number | Sector;
  /**
   * Show in the homepage carousel.
   */
  featured?: boolean | null;
  /**
   * Lower numbers are listed first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for people who cannot see it.
   */
  alt: string;
  caption?: string | null;
  /**
   * Leave empty for group-wide content.
   */
  business?: (number | null) | Business;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RatesTableBlock".
 */
export interface RatesTableBlock {
  heading?: string | null;
  /**
   * Rates are shown as this currency per 1 unit.
   */
  baseCurrency?: string | null;
  updatedAt?: string | null;
  rates?:
    | {
        code: string;
        currency: string;
        buy?: number | null;
        sell?: number | null;
        id?: string | null;
      }[]
    | null;
  note?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'ratesTable';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LoanProductsBlock".
 */
export interface LoanProductsBlock {
  heading?: string | null;
  intro?: string | null;
  products?:
    | {
        name: string;
        description?: string | null;
        amountRange?: string | null;
        /**
         * Say per month or per year, and flat or reducing balance.
         */
        interestRate?: string | null;
        term?: string | null;
        id?: string | null;
      }[]
    | null;
  requirements?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  terms?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'loanProducts';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProductListBlock".
 */
export interface ProductListBlock {
  heading?: string | null;
  intro?: string | null;
  products?:
    | {
        name: string;
        size?: string | null;
        pack?: string | null;
        price?: string | null;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * e.g. "Prices include GST and may change."
   */
  note?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'productList';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RoomsBlock".
 */
export interface RoomsBlock {
  heading?: string | null;
  rooms?:
    | {
        name: string;
        description?: string | null;
        capacity?: string | null;
        rate?: string | null;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  amenities?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'rooms';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FAQBlock".
 */
export interface FAQBlock {
  heading?: string | null;
  items?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'faq';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CTABlock".
 */
export interface CTABlock {
  heading: string;
  text?: string | null;
  link: {
    label: string;
    /**
     * A page on this site (e.g. /businesses) or a full web address.
     */
    url: string;
  };
  style?: ('dark' | 'light') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock".
 */
export interface RichTextBlock {
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'richText';
}
/**
 * Groups businesses on the site, e.g. Energy, Hospitality.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sectors".
 */
export interface Sector {
  id: number;
  name: string;
  description?: string | null;
  image?: (number | null) | Media;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  title: string;
  /**
   * Shown on cards and in search results.
   */
  excerpt: string;
  heroImage: number | Media;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  category: 'news' | 'press' | 'story';
  /**
   * Leave empty for group-wide content.
   */
  business?: (number | null) | Business;
  sectors?: (number | Sector)[] | null;
  author?: string | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Foundation / CSR programmes and stories, shown under /impact.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "impact-programmes".
 */
export interface ImpactProgramme {
  id: number;
  title: string;
  summary: string;
  heroImage?: (number | null) | Media;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  stats?:
    | {
        /**
         * e.g. 16, 250+, 24/7
         */
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  gallery?: (number | Media)[] | null;
  partners?:
    | {
        name: string;
        logo?: (number | null) | Media;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  pillar: 'education' | 'health' | 'environment' | 'enterprise' | 'community';
  /**
   * Optional: the business behind this programme.
   */
  business?: (number | null) | Business;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leadership".
 */
export interface Leadership {
  id: number;
  name: string;
  title: string;
  photo?: (number | null) | Media;
  bio?: string | null;
  group: 'executive' | 'board';
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Flexible pages such as About, Privacy and Terms.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  layout?: (HeroBlock | RichTextBlock | ServicesGridBlock | StatsBlock | GalleryBlock | CTABlock | FAQBlock)[] | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  eyebrow?: string | null;
  heading: string;
  subheading?: string | null;
  image?: (number | null) | Media;
  cta?: {
    label?: string | null;
    /**
     * A page on this site (e.g. /businesses) or a full web address.
     */
    url?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ServicesGridBlock".
 */
export interface ServicesGridBlock {
  heading?: string | null;
  intro?: string | null;
  items?:
    | {
        title: string;
        description?: string | null;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'servicesGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBlock".
 */
export interface StatsBlock {
  heading?: string | null;
  stats?:
    | {
        /**
         * e.g. 16, 250+, 24/7
         */
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'stats';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryBlock".
 */
export interface GalleryBlock {
  heading?: string | null;
  images: (number | Media)[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'gallery';
}
/**
 * Messages sent through the website. Update the status as you follow up.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries".
 */
export interface Enquiry {
  id: number;
  name: string;
  email: string;
  phone?: string | null;
  message: string;
  pageUrl?: string | null;
  /**
   * Empty for general group enquiries.
   */
  business?: (number | null) | Business;
  type: 'general' | 'sales' | 'partnership' | 'media';
  status: 'new' | 'in-progress' | 'closed' | 'spam';
  /**
   * Only visible to staff.
   */
  internalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Super admin: everything. Group editor: all content. Business editor: only the businesses below.
   */
  role: 'super-admin' | 'group-editor' | 'business-editor';
  /**
   * Business editors can only edit these businesses and their news and enquiries.
   */
  tenants?:
    | {
        tenant: number | Business;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'businesses';
          value: number | Business;
        } | null)
      | ({
          relationTo: 'news';
          value: number | News;
        } | null)
      | ({
          relationTo: 'impact-programmes';
          value: number | ImpactProgramme;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'businesses';
        value: number | Business;
      } | null)
    | ({
        relationTo: 'sectors';
        value: number | Sector;
      } | null)
    | ({
        relationTo: 'news';
        value: number | News;
      } | null)
    | ({
        relationTo: 'impact-programmes';
        value: number | ImpactProgramme;
      } | null)
    | ({
        relationTo: 'leadership';
        value: number | Leadership;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'enquiries';
        value: number | Enquiry;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "businesses_select".
 */
export interface BusinessesSelect<T extends boolean = true> {
  name?: T;
  tagline?: T;
  summary?: T;
  logo?: T;
  heroImage?: T;
  overview?: T;
  services?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        id?: T;
      };
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  gallery?: T;
  layout?:
    | T
    | {
        ratesTable?: T | RatesTableBlockSelect<T>;
        loanProducts?: T | LoanProductsBlockSelect<T>;
        productList?: T | ProductListBlockSelect<T>;
        rooms?: T | RoomsBlockSelect<T>;
        faq?: T | FAQBlockSelect<T>;
        cta?: T | CTABlockSelect<T>;
        richText?: T | RichTextBlockSelect<T>;
      };
  locations?:
    | T
    | {
        name?: T;
        district?: T;
        address?: T;
        phone?: T;
        hours?: T;
        lat?: T;
        lng?: T;
        id?: T;
      };
  contact?:
    | T
    | {
        phone?: T;
        whatsapp?: T;
        email?: T;
        enquiryEmail?: T;
      };
  socials?:
    | T
    | {
        facebook?: T;
        instagram?: T;
        linkedin?: T;
        tiktok?: T;
        x?: T;
        youtube?: T;
      };
  website?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  generateSlug?: T;
  slug?: T;
  sector?: T;
  featured?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RatesTableBlock_select".
 */
export interface RatesTableBlockSelect<T extends boolean = true> {
  heading?: T;
  baseCurrency?: T;
  updatedAt?: T;
  rates?:
    | T
    | {
        code?: T;
        currency?: T;
        buy?: T;
        sell?: T;
        id?: T;
      };
  note?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LoanProductsBlock_select".
 */
export interface LoanProductsBlockSelect<T extends boolean = true> {
  heading?: T;
  intro?: T;
  products?:
    | T
    | {
        name?: T;
        description?: T;
        amountRange?: T;
        interestRate?: T;
        term?: T;
        id?: T;
      };
  requirements?:
    | T
    | {
        item?: T;
        id?: T;
      };
  terms?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProductListBlock_select".
 */
export interface ProductListBlockSelect<T extends boolean = true> {
  heading?: T;
  intro?: T;
  products?:
    | T
    | {
        name?: T;
        size?: T;
        pack?: T;
        price?: T;
        image?: T;
        id?: T;
      };
  note?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RoomsBlock_select".
 */
export interface RoomsBlockSelect<T extends boolean = true> {
  heading?: T;
  rooms?:
    | T
    | {
        name?: T;
        description?: T;
        capacity?: T;
        rate?: T;
        image?: T;
        id?: T;
      };
  amenities?:
    | T
    | {
        item?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FAQBlock_select".
 */
export interface FAQBlockSelect<T extends boolean = true> {
  heading?: T;
  items?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CTABlock_select".
 */
export interface CTABlockSelect<T extends boolean = true> {
  heading?: T;
  text?: T;
  link?:
    | T
    | {
        label?: T;
        url?: T;
      };
  style?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock_select".
 */
export interface RichTextBlockSelect<T extends boolean = true> {
  content?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sectors_select".
 */
export interface SectorsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  image?: T;
  generateSlug?: T;
  slug?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  heroImage?: T;
  body?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  generateSlug?: T;
  slug?: T;
  category?: T;
  business?: T;
  sectors?: T;
  author?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "impact-programmes_select".
 */
export interface ImpactProgrammesSelect<T extends boolean = true> {
  title?: T;
  summary?: T;
  heroImage?: T;
  body?: T;
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  gallery?: T;
  partners?:
    | T
    | {
        name?: T;
        logo?: T;
        url?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  generateSlug?: T;
  slug?: T;
  pillar?: T;
  business?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leadership_select".
 */
export interface LeadershipSelect<T extends boolean = true> {
  name?: T;
  title?: T;
  photo?: T;
  bio?: T;
  group?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  layout?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        richText?: T | RichTextBlockSelect<T>;
        servicesGrid?: T | ServicesGridBlockSelect<T>;
        stats?: T | StatsBlockSelect<T>;
        gallery?: T | GalleryBlockSelect<T>;
        cta?: T | CTABlockSelect<T>;
        faq?: T | FAQBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  subheading?: T;
  image?: T;
  cta?:
    | T
    | {
        label?: T;
        url?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ServicesGridBlock_select".
 */
export interface ServicesGridBlockSelect<T extends boolean = true> {
  heading?: T;
  intro?: T;
  items?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBlock_select".
 */
export interface StatsBlockSelect<T extends boolean = true> {
  heading?: T;
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryBlock_select".
 */
export interface GalleryBlockSelect<T extends boolean = true> {
  heading?: T;
  images?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries_select".
 */
export interface EnquiriesSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  message?: T;
  pageUrl?: T;
  business?: T;
  type?: T;
  status?: T;
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  business?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  tenants?:
    | T
    | {
        tenant?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  hero: {
    eyebrow?: string | null;
    headline: string;
    subline?: string | null;
    image?: (number | null) | Media;
    primaryCta?: {
      label?: string | null;
      /**
       * A page on this site (e.g. /businesses) or a full web address.
       */
      url?: string | null;
    };
    secondaryCta?: {
      label?: string | null;
      /**
       * A page on this site (e.g. /businesses) or a full web address.
       */
      url?: string | null;
    };
  };
  /**
   * Leave empty to use businesses marked "featured".
   */
  featuredBusinesses?: (number | Business)[] | null;
  featuredImpact?: (number | null) | ImpactProgramme;
  chairman?: {
    quote?: string | null;
    name?: string | null;
    title?: string | null;
    portrait?: (number | null) | Media;
    link?: {
      label?: string | null;
      /**
       * A page on this site (e.g. /businesses) or a full web address.
       */
      url?: string | null;
    };
  };
  ctaBand?: {
    heading?: string | null;
    text?: string | null;
    link?: {
      label?: string | null;
      /**
       * A page on this site (e.g. /businesses) or a full web address.
       */
      url?: string | null;
    };
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Shown at /news/media-kit.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-kit".
 */
export interface MediaKit {
  id: number;
  boilerplate?: string | null;
  logos?:
    | {
        label: string;
        file: number | Media;
        id?: string | null;
      }[]
    | null;
  brandGuidelines?: (number | null) | Media;
  pressContact?: {
    name?: string | null;
    email?: string | null;
    phone?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  groupName: string;
  contact?: {
    address?: string | null;
    phone?: string | null;
    whatsapp?: string | null;
    email?: string | null;
    /**
     * General enquiries go here; business enquiries are copied here too.
     */
    enquiryEmail?: string | null;
  };
  socials?: {
    facebook?: string | null;
    instagram?: string | null;
    linkedin?: string | null;
    tiktok?: string | null;
    x?: string | null;
    youtube?: string | null;
  };
  /**
   * Numbers shown on the homepage, e.g. 16 businesses, 8 sectors.
   */
  stats?:
    | {
        /**
         * e.g. 16, 250+, 24/7
         */
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  navItems?:
    | {
        link: {
          label: string;
          /**
           * A page on this site (e.g. /businesses) or a full web address.
           */
          url: string;
        };
        id?: string | null;
      }[]
    | null;
  cta?: {
    label?: string | null;
    /**
     * A page on this site (e.g. /businesses) or a full web address.
     */
    url?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Businesses are listed by sector automatically.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  tagline?: string | null;
  legalLinks?:
    | {
        link: {
          label: string;
          /**
           * A page on this site (e.g. /businesses) or a full web address.
           */
          url: string;
        };
        id?: string | null;
      }[]
    | null;
  showNewsletter?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        subline?: T;
        image?: T;
        primaryCta?:
          | T
          | {
              label?: T;
              url?: T;
            };
        secondaryCta?:
          | T
          | {
              label?: T;
              url?: T;
            };
      };
  featuredBusinesses?: T;
  featuredImpact?: T;
  chairman?:
    | T
    | {
        quote?: T;
        name?: T;
        title?: T;
        portrait?: T;
        link?:
          | T
          | {
              label?: T;
              url?: T;
            };
      };
  ctaBand?:
    | T
    | {
        heading?: T;
        text?: T;
        link?:
          | T
          | {
              label?: T;
              url?: T;
            };
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-kit_select".
 */
export interface MediaKitSelect<T extends boolean = true> {
  boilerplate?: T;
  logos?:
    | T
    | {
        label?: T;
        file?: T;
        id?: T;
      };
  brandGuidelines?: T;
  pressContact?:
    | T
    | {
        name?: T;
        email?: T;
        phone?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  groupName?: T;
  contact?:
    | T
    | {
        address?: T;
        phone?: T;
        whatsapp?: T;
        email?: T;
        enquiryEmail?: T;
      };
  socials?:
    | T
    | {
        facebook?: T;
        instagram?: T;
        linkedin?: T;
        tiktok?: T;
        x?: T;
        youtube?: T;
      };
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              label?: T;
              url?: T;
            };
        id?: T;
      };
  cta?:
    | T
    | {
        label?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  tagline?: T;
  legalLinks?:
    | T
    | {
        link?:
          | T
          | {
              label?: T;
              url?: T;
            };
        id?: T;
      };
  showNewsletter?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'businesses';
          value: number | Business;
        } | null)
      | ({
          relationTo: 'news';
          value: number | News;
        } | null);
    global?: string | null;
    user?: {
      relationTo: 'users';
      value: number | User;
    } | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}